language: php
php:
  - "8.0"
  - "8.1"
  - "8.2"
  - "8.3"
  - "8.4"
dist: precise
install:
  - composer install
script: composer test -- --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
